### ISSUE TITLE
android集成v4版本时，找不到CustomDeviceInfos

### ISSUE THREAD

**Issue by afunx** [xingePush/xinge_android_demo#4]
按照官网集成android v4的方法，调用注册接口：
        XGPushManager.registerPush(this, new XGIOperateCallback(){

            @Override
            public void onSuccess(Object o, int i) {
                LogUtils.e("afunx", "onSuccess");
            }

            @Override
            public void onFail(Object o, int i, String s) {
                LogUtils.e("afunx", "onFail");
            }
        });

产生如下错误：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/tencent/bigdata/dataacquisition/CustomDeviceInfos;

但是，参考这个demo，使用v3时，就不会有这个问题。

**Comment by captain-miao** [comment]
为何直接关闭了，一样的问题～
